# Generated by Django 4.2.13 on 2024-07-02 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_remove_room_guest_remove_room_reservation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_description', models.TextField(blank=True, null=True)),
                ('place', models.IntegerField()),
                ('area', models.IntegerField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='room_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_description',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_image',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_price',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel_app.roomtype'),
        ),
    ]
