# Generated by Django 4.2.13 on 2024-07-02 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel_app', '0003_roomtype_remove_room_room_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='guest',
        ),
        migrations.AddField(
            model_name='reservation',
            name='guests',
            field=models.ManyToManyField(related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='hotel_app.room'),
            preserve_default=False,
        ),
    ]
